"""add avatar_key to user

Revision ID: bf9f870a3277
Revises: 98021bda8a66
Create Date: 2026-05-14 18:55:01.300104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf9f870a3277'
down_revision = '98021bda8a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('avatar_key', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('email')
    )
    op.create_table('Client',
    sa.Column('clientID', sa.Integer(), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['User.userID'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('clientID')
    )
    op.create_table('HairProfiles',
    sa.Column('profileID', sa.Integer(), nullable=False),
    sa.Column('clientID', sa.Integer(), nullable=False),
    sa.Column('natural_colour', sa.String(length=50), nullable=True),
    sa.Column('current_colour', sa.String(length=50), nullable=True),
    sa.Column('texture', sa.String(length=50), nullable=True),
    sa.Column('porosity', sa.String(length=50), nullable=True),
    sa.Column('chem_history', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['clientID'], ['Client.clientID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profileID')
    )
    op.create_table('DyeSession',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('profileID', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('desired_shade', sa.String(length=50), nullable=True),
    sa.Column('developer_vol', sa.Integer(), nullable=True),
    sa.Column('input_hair_pic_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['profileID'], ['HairProfiles.profileID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('StrandPredictions',
    sa.Column('predictionID', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('predicted_colour', sa.String(length=50), nullable=True),
    sa.Column('damage_risk', sa.String(length=50), nullable=True),
    sa.Column('damage_score', sa.Float(), nullable=True),
    sa.Column('process_time', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('test_date', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('output_hair_pic_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['DyeSession.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('predictionID')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('email'))

    op.drop_table('user')
    op.drop_table('dyesession')
    op.drop_table('hairprofiles')
    op.drop_table('strandpredictions')
    op.drop_table('client')
    with op.batch_alter_table('formulaarchive', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('formulaarchive_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'DyeSession', ['session_id'], ['session_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('formulaarchive', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('formulaarchive_ibfk_1'), 'dyesession', ['session_id'], ['session_id'], ondelete='CASCADE')

    op.create_table('client',
    sa.Column('clientID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('client_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('userID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], name=op.f('client_ibfk_1'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('clientID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('strandpredictions',
    sa.Column('predictionID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('predicted_colour', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('damage_risk', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('damage_score', mysql.FLOAT(), nullable=True),
    sa.Column('process_time', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('success_rate', mysql.FLOAT(), nullable=True),
    sa.Column('test_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('output_hair_pic_url', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['dyesession.session_id'], name=op.f('strandpredictions_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('predictionID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('hairprofiles',
    sa.Column('profileID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clientID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('natural_colour', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('current_colour', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('texture', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('porosity', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('chem_history', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['clientID'], ['client.clientID'], name=op.f('hairprofiles_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profileID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dyesession',
    sa.Column('session_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('profileID', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('desired_shade', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('developer_vol', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('input_hair_pic_url', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['profileID'], ['hairprofiles.profileID'], name=op.f('dyesession_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('userID', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('userID'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('email'), ['email'], unique=True)

    op.drop_table('StrandPredictions')
    op.drop_table('DyeSession')
    op.drop_table('HairProfiles')
    op.drop_table('Client')
    op.drop_table('User')
    # ### end Alembic commands ###
