"""add session fields

Revision ID: e8aa3d1339e3
Revises: bf9f870a3277
Create Date: 2026-05-15 00:44:17.957920

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8aa3d1339e3'
down_revision = 'bf9f870a3277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dyesession', schema=None) as batch_op:
        batch_op.add_column(sa.Column('after_hair_pic_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('slvl', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tlvl', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('outcome', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('stars', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dyesession', schema=None) as batch_op:
        batch_op.drop_column('stars')
        batch_op.drop_column('notes')
        batch_op.drop_column('outcome')
        batch_op.drop_column('tlvl')
        batch_op.drop_column('slvl')
        batch_op.drop_column('after_hair_pic_url')

    # ### end Alembic commands ###
